source 'https://rubygems.org'

# This Gemfile is for TESTING really. 
# Not sure it has any use for anyone just wanting to use this gem

# DEFINE VERSIONS YOU WANT TO TEST AGAINST HERE
# THIS SHOULD BASICALLY REPLICATE WHAT IS IN THE SANDBOX GEMFILE

gem 'rails', '4.0.5'


#if(File.exists?('/home/ruby_user/SoftwareDev/git/datashift'))
#gem 'datashift',  :path => "/home/ruby_user/SoftwareDev/git/datashift"
#else
gem 'datashift', "0.16.0"
#end


# we want to test both JRuby and non JRuby especially for Excel

platform :jruby do
  gem 'jruby-openssl'
  gem 'activerecord-jdbcsqlite3-adapter'
end

platform :ruby do
  gem 'sqlite3'
  #gem "debugger"
end

# FROM SANDBOX GEMFILE

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end


#DATASHIFT TESTING
#
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby


gem 'spree', '2.2.2'

# N.B Spree will update the sandbox Gemfile with additional Spree gems 
# e,g User model and Authorisation 
# For rspec you  may need to add them in here or you'll get missing Spree constants  
#TODO - update  sandbox code so it automatically adds Spree gems in here

gem 'spree_gateway', :git => 'https://github.com/spree/spree_gateway.git', :branch => '2-2-stable'
gem 'spree_auth_devise', :git => 'https://github.com/spree/spree_auth_devise.git', :branch => '2-2-stable'


# gem 'spree_auth_devise'
# #gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-0-stable'

gem 'mechanize'

# STATIC GEMS

gem 'rspec'  # Behavior Driven Development (BDD) for Ruby
gem 'rspec-core'  # RSpec runner and example groups.
gem 'rspec-expectations'  # RSpec matchers for should and should_not.
gem 'rspec-mocks'  # RSpec test double framework with stubbing and mocking.
gem 'rspec-rails'  # RSpec version 2.x for Rails version 3.x.


